version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gamerbox-backend/public:/var/www/public
      - ./gamerbox-backend/public/uploads:/var/www/public/uploads
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./gamerbox-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./gamerbox-frontend:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - app-network

  backend:
    build:
      context: ./gamerbox-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gamerbox-backend:/var/www
      - ./gamerbox-backend/public/uploads:/var/www/public/uploads
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://root:@db:3306/gamerbox?serverVersion=8.0.32&charset=utf8mb4
      - JWT_SECRET_KEY=/var/www/config/jwt/private.pem
      - JWT_PUBLIC_KEY=/var/www/config/jwt/public.pem
      - JWT_PASSPHRASE=gamerbox
      - APP_SECRET=gamerbox_secret_key
    networks:
      - app-network
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gamerbox
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
    depends_on:
      - db
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --force-renewal --email tu-email@ejemplo.com -d tu-dominio.com -d www.tu-dominio.com --agree-tos --no-eff-email

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=tu-subdominio
      - TOKEN=tu-token
      - LOG_FILE=false
    volumes:
      - ./duckdns:/config
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
