nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "Accept", "Origin", "X-Requested-With"]
    expose_headers: ["Authorization"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/": null