security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\JWTAuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
            
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/profile, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/.+/favorites$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users/.+/superfavorites$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users, roles: PUBLIC_ACCESS }
        - { path: ^/api/games, roles: PUBLIC_ACCESS }
        - { path: ^/api/genres, roles: PUBLIC_ACCESS }
        - { path: ^/api/platforms, roles: PUBLIC_ACCESS }
        - { path: ^/api/comments, roles: PUBLIC_ACCESS }
        - { path: ^/api/lists/recent$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/lists$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/lists/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/reviews$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/reviews/following$, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
        - { path: ^/api/games/.+/reviews$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users/.+/reviews$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/reviews/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/reviews/.+/comments$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/games/.+/favorite$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/games/.+/favorite$, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api/games/.+/superfavorite$, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api/lists, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api/lists/\d+, roles: IS_AUTHENTICATED_FULLY, methods: [PUT, DELETE] }
        - { path: ^/api/lists/\d+/games, roles: IS_AUTHENTICATED_FULLY, methods: [POST, DELETE] }
        - { path: ^/api/users/.+/lists$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/reviews, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/reviews/.+/comments$, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
